algoritmo "semnome"
// Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
// qualquer e mostre uma contagem até esse valor:
// Ex: Digite um valor: 35
// Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!

var
    n: inteiro
    
procedimento contagemAte(v: inteiro)
var
cont: inteiro
inicio
    para cont <- 0 ate v faca
        escreva(cont)
    fimpara
fimprocedimento
inicio

      contagemAte(22)


fimalgoritmo


